function rng(seed){let x=seed>>>0;return()=>{x^=(x<<13);x^=x>>>17;x^=(x<<5);return x>>>0}}

function permute(n,R){const p=Array.from({length:n},(_,i)=>i);for(let i=n-1;i>0;i--){let j=R()%(i+1);[p[i],p[j]]=[p[j],p[i]]}return p}

function parts(n,p,q){let unseen=new Set(Array.from({length:n},(_,i)=>i)),out=[];while(unseen.size){let root=Math.min(...unseen),queue=[root],part=new Set([root]);for(let k=0;k<queue.length;k++){let u=queue[k];for(const v of [p[u],q[u]])if(!part.has(v)){part.add(v);queue.push(v)}}for(const x of part)unseen.delete(x);out.push([...part])}return out}

function rank(n,p,q){const edges=[],ind=new Map();for(let u=0;u<n;u++)for(let v=u+1;v<n;v++){ind.set(u*n+v,edges.length);edges.push([u,v])}const E=edges.length,P=Array.from({length:E+1},(_,i)=>i);const find=x=>{while(P[x]!==x){P[x]=P[P[x]];x=P[x]}return x};const key=(u,v)=>u===v?E:ind.get(Math.min(u,v)*n+Math.max(u,v));for(let u=0;u<n;u++)for(let v=0;v<n;v++){let a=find(key(u,v)),b=find(key(p[u],q[v]));if(a!==b)P[a]=b}const z=find(E),free=[...new Set(Array.from({length:E},(_,i)=>find(i)))].filter(x=>x!==z).length;return E-free}

function independentBound(n,p,q){const moved=Array.from({length:n},(_,i)=>i).filter(i=>p[i]!==i),rest=Array.from({length:n},(_,i)=>i).filter(i=>p[i]===i),order=[...moved,...rest],seen=new Set(moved);let M=0,taut=0,eq=[];const key=(u,v)=>Math.min(u,v)*n+Math.max(u,v);for(let i=0;i<n;i++){let u=order[i];if(!seen.has(u))break;for(let j=i+1;j<n;j++){let v=order[j];M++;let a=key(u,v),b=p[u]===q[v]?null:key(p[u],q[v]);if(a===b){taut++;continue}eq.push(b===null?[a]:[a,b])}}const deg=new Map();for(let e of eq)for(let v of e)deg.set(v,(deg.get(v)||0)+1);if(Math.max(0,...deg.values())>3)throw Error("variable incidence >3");let used=new Set(),picked=0;for(let e of eq)if(e.every(v=>!used.has(v))){picked++;e.forEach(v=>used.add(v))}let a=moved.length;if(M!==a*(n-a)+a*(a-1)/2||taut>a||6*picked<M-a)throw Error("matching lower bound failed");return{a,M,taut,picked}}

function perm4(){const out=[];function go(xs,acc){if(!xs.length){out.push(acc);return}for(let i=0;i<xs.length;i++)go([...xs.slice(0,i),...xs.slice(i+1)],[...acc,xs[i]])}go([0,1,2,3],[]);return out}

function check4(){const perms=perm4(),counts={"t1_true":0,"t2_true":0,"t1_false":0,"t2_false":0},maskcounts={"t1":0,"t2":0};const es=[[0,1],[0,2],[0,3],[1,2],[1,3],[2,3]];for(const p of perms)for(const q of perms){if(p.every((x,i)=>x===q[i])||p.every((x,i)=>x===i&&q[i]===i))continue;let s=Array.from({length:4},(_,i)=>i).filter(i=>p[i]!==i||q[i]!==i).length;if(s!==4)continue;const orbs=parts(4,p,q),t=orbs.length;let valid=0;for(let mask=0;mask<64;mask++){const A=Array.from({length:4},()=>Array(4).fill(0));es.forEach(([u,v],k)=>{A[u][v]=A[v][u]=(mask>>k)&1});if(!Array.from({length:4},(_,u)=>Array.from({length:4},(_,v)=>A[u][v]===A[p[u]][q[v]]).every(Boolean)).every(Boolean))continue;const forced=orbs.some(o=>o.some((a,i)=>o.slice(i+1).some(b=>Array.from({length:4},(_,w)=>A[a][w]===A[b][w]).every(Boolean))));if(!forced)valid++}counts["t"+t+"_"+(valid>0?"true":"false")]++;if(valid>0)maskcounts["t"+t]+=valid;if(valid>0&&t===2){let sa=p.filter((v,i)=>v!==i).length,sb=q.filter((v,i)=>v!==i).length;if(sa!==2||sb!==2||Array.from({length:4},(_,i)=>i).some(i=>p[i]!==i&&q[i]!==i))throw Error("nonleading two-orbit support")}}if(counts.t2_true!==6||counts.t1_true!==30||maskcounts.t2!==12||maskcounts.t1!==36)throw Error("four-point results mismatch "+JSON.stringify({counts,maskcounts}));return{counts,maskcounts}}

function run(){const R=rng(20261010);let total=0,bySize=[];for(const n of [6,7,8,10,12,16,20,24]){let checked=0;for(let i=0;i<350;i++){let p=permute(n,R),q=permute(n,R);if(p.every((v,j)=>v===q[j]))continue;let moved=Array.from({length:n},(_,j)=>j).filter(j=>p[j]!==j||q[j]!==j),s=moved.length,t=parts(n,p,q).filter(o=>o.some(j=>p[j]!==j||q[j]!==j)).length;let loss=rank(n,p,q);if(loss<(s-t)*(n-s))throw Error("orbit-bit-loss lower bound failed");let r=independentBound(n,p,q);if(loss<r.picked)throw Error("rank less than matching lower bound");checked++}bySize.push({n,checked});total+=checked}const four=check4();return {source:"raw ordered TF edge equations; not the discovery algorithm",seed:20261010,totalPermutationPairs:total,bySize,completeFourVertexClassification:four,negativeControls:"constraint degree and twin obstruction asserted",result:"PASS"}}

console.log(JSON.stringify(run(),null,2));
